version: '3'
services:
  db:
    build:
      context: ./back-end/src/main/java/Repository
      dockerfile: Dockerfile
    ports:
      - 3306:3306
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
#  frontend:
#    build:
#      context: ./front-end/myapp
#      dockerfile: Dockerfile
#    ports:
#      - 3000:80
#    depends_on:
#      - backend
